# Generated by Django 2.2.13 on 2021-02-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientipaddress',
            name='asname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='countryCode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='isp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='org',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='regionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='zip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
