# Generated by Django 2.2.13 on 2021-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_info',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
