# Generated by Django 2.2.13 on 2021-02-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210213_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_info',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
