# Generated by Django 2.2.13 on 2021-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('host_address', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('meas_time', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'ordering': ['-meas_time'],
            },
        ),
    ]
