# Generated by Django 2.2.13 on 2021-02-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhouseweatherapp', '0003_clientipaddress_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientipaddress',
            name='host_address',
        ),
    ]
