# Generated by Django 2.2.13 on 2021-02-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhouseweatherapp', '0004_remove_clientipaddress_host_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientipaddress',
            name='absolute_uri',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientipaddress',
            name='map_link',
            field=models.TextField(null=True),
        ),
    ]
