# Generated by Django 4.2.24 on 2026-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GustoPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_member', models.CharField(max_length=255)),
                ('employee_initials', models.CharField(max_length=8, null=True)),
                ('payroll_period', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_hours', models.FloatField(blank=True, null=True)),
                ('regular_amount', models.FloatField(blank=True, null=True)),
                ('regular_rate', models.FloatField(blank=True, null=True)),
                ('time_off_hours', models.FloatField(blank=True, null=True)),
                ('time_off_amount', models.FloatField(blank=True, null=True)),
                ('time_off_rate', models.FloatField(blank=True, null=True)),
                ('additional_earnings', models.FloatField(blank=True, null=True)),
                ('gross_earnings', models.FloatField(blank=True, null=True)),
                ('employee_taxes', models.FloatField(blank=True, null=True)),
                ('federal_income_tax_employee', models.FloatField(blank=True, null=True)),
                ('social_security_employee', models.FloatField(blank=True, null=True)),
                ('medicare_employee', models.FloatField(blank=True, null=True)),
                ('additional_medicare_employee', models.FloatField(blank=True, null=True)),
                ('employer_taxes', models.FloatField(blank=True, null=True)),
                ('social_security_employer', models.FloatField(blank=True, null=True)),
                ('medicare_employer', models.FloatField(blank=True, null=True)),
                ('tx_suta_employer', models.FloatField(blank=True, null=True)),
                ('futa_employer', models.FloatField(blank=True, null=True)),
                ('net_pay', models.FloatField(blank=True, null=True)),
                ('reimbursements', models.FloatField(blank=True, null=True)),
                ('donations', models.FloatField(blank=True, null=True)),
                ('check_amount', models.FloatField(blank=True, null=True)),
                ('employer_cost', models.FloatField(blank=True, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_period_start', models.DateField(blank=True, null=True)),
                ('payroll_period_end', models.DateField(blank=True, null=True)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
