# Generated by Django 4.2.24 on 2026-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GustoPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_member', models.CharField(max_length=255)),
                ('employee_initials', models.CharField(max_length=8, null=True)),
                ('payroll_period', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_hours', models.FloatField(blank=True, null=True)),
                ('regular_amount', models.FloatField(blank=True, null=True)),
                ('regular_rate', models.FloatField(blank=True, null=True)),
                ('time_off_hours', models.FloatField(blank=True, null=True)),
                ('time_off_amount', models.FloatField(blank=True, null=True)),
                ('time_off_rate', models.FloatField(blank=True, null=True)),
                ('additional_earnings', models.FloatField(blank=True, null=True)),
                ('gross_earnings', models.FloatField(blank=True, null=True)),
                ('employee_taxes', models.FloatField(blank=True, null=True)),
                ('federal_income_tax_employee', models.FloatField(blank=True, null=True)),
                ('social_security_employee', models.FloatField(blank=True, null=True)),
                ('medicare_employee', models.FloatField(blank=True, null=True)),
                ('additional_medicare_employee', models.FloatField(blank=True, null=True)),
                ('employer_taxes', models.FloatField(blank=True, null=True)),
                ('social_security_employer', models.FloatField(blank=True, null=True)),
                ('medicare_employer', models.FloatField(blank=True, null=True)),
                ('tx_suta_employer', models.FloatField(blank=True, null=True)),
                ('futa_employer', models.FloatField(blank=True, null=True)),
                ('net_pay', models.FloatField(blank=True, null=True)),
                ('reimbursements', models.FloatField(blank=True, null=True)),
                ('donations', models.FloatField(blank=True, null=True)),
                ('check_amount', models.FloatField(blank=True, null=True)),
                ('employer_cost', models.FloatField(blank=True, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_period_start', models.DateField(blank=True, null=True)),
                ('payroll_period_end', models.DateField(blank=True, null=True)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JaneProcessedClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('applied_to', models.TextField(blank=True, null=True)),
                ('claim_count', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('processing_fee', models.FloatField(blank=True, null=True)),
                ('amount_paid_to_clinic', models.FloatField(blank=True, null=True)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JaneSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_member', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_initials', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('collected', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XeroTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('related_account', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('gross', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_key', models.CharField(max_length=64, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
