# Generated by Django 4.2.24 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_dash_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='janesessions',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='janesessions',
            name='payer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
