# Generated by Django 4.2.24 on 2026-09-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_dash_pro', '0002_janesessions_invoice_number_janesessions_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='janesessions',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
