# Generated by Django 2.2.13 on 2021-02-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=50)),
                ('Posting_Date', models.DateTimeField()),
                ('Description', models.TextField()),
                ('Amount', models.FloatField()),
                ('Type', models.CharField(max_length=150)),
                ('Balance', models.FloatField(blank=True)),
                ('Check_Slip', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['-Posting_Date'],
            },
        ),
    ]
