# Generated by Django 4.2.24 on 2025-11-20 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=155)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=50)),
                ('Posting_Date', models.DateTimeField()),
                ('Description', models.TextField()),
                ('Amount', models.FloatField()),
                ('Type', models.CharField(max_length=150)),
                ('Balance', models.FloatField(blank=True)),
                ('Check_Slip', models.TextField(blank=True)),
                ('Insert_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(default='gfp.1@hotmail.com', on_delete=django.db.models.deletion.CASCADE, to='myfinances.users')),
            ],
            options={
                'ordering': ['-Posting_Date'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.TextField()),
                ('Expression', models.TextField()),
                ('Class', models.CharField(default='Non-categorized', max_length=254)),
                ('Insert_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinances.users')),
            ],
            options={
                'ordering': ['Group'],
            },
        ),
    ]
