# Generated by Django 2.2.13 on 2021-02-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.TextField()),
                ('Expression', models.TextField()),
            ],
            options={
                'ordering': ['-Group'],
            },
        ),
    ]
