# Generated by Django 4.2.24 on 2025-11-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinances.users'),
        ),
    ]
