# Generated by Django 2.2.13 on 2021-02-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=155)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['Group']},
        ),
        migrations.AddField(
            model_name='categories',
            name='Class',
            field=models.CharField(default='Non-categorized', max_length=254),
        ),
        migrations.AddField(
            model_name='categories',
            name='Owner',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='myfinances.Users'),
        ),
    ]
