# Generated by Django 4.2.24 on 2025-11-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0002_alter_statements_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='Owner',
        ),
    ]
