# Generated by Django 2.2.13 on 2021-02-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0003_auto_20210223_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinances.Users'),
        ),
    ]
