# Generated by Django 4.2.24 on 2025-11-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0004_statements_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myfinances.categories'),
        ),
    ]
