# Generated by Django 4.2.24 on 2025-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0005_item_categories_insert_date_alter_categories_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Update_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
