# Generated by Django 4.2.24 on 2025-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0005_statements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Posting_Date',
            field=models.DateField(),
        ),
    ]
