# Generated by Django 4.2.24 on 2025-11-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0006_alter_statements_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Owner',
            field=models.ForeignKey(default='admin@mywebsite.com', on_delete=django.db.models.deletion.CASCADE, to='myfinances.users'),
        ),
    ]
