# Generated by Django 4.2.24 on 2025-11-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0007_alter_statements_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Owner',
            field=models.ForeignKey(default='gfp.1@hotmail.com', on_delete=django.db.models.deletion.CASCADE, to='myfinances.users'),
        ),
    ]
