# Generated by Django 4.2.24 on 2025-11-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myfinances', '0009_alter_statements_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
