# Generated by Django 4.2.24 on 2025-11-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0011_categorylist_categorylist_unique_category_per_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myfinances.categorylist'),
        ),
    ]
