# Generated by Django 4.2.24 on 2025-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0013_alter_categorylist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='Acct_Info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
