# Generated by Django 4.2.24 on 2025-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0014_statements_acct_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Acct_Info',
            field=models.CharField(max_length=20),
        ),
    ]
