# Generated by Django 4.2.24 on 2025-12-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0015_alter_statements_acct_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='label',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Other', 'Other')], default='Other', help_text='Assign a label to classify this category (e.g., Income, Expense, Asset, Liability).', max_length=50),
        ),
        migrations.AlterField(
            model_name='statements',
            name='Acct_Info',
            field=models.CharField(max_length=4),
        ),
    ]
