# Generated by Django 4.2.24 on 2025-12-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myfinances', '0016_categorylist_label_alter_statements_acct_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='user_group',
            field=models.ForeignKey(default=1, help_text='User group that owns this transaction; all users in the group share access.', on_delete=django.db.models.deletion.CASCADE, related_name='user_group_statements', to='auth.group'),
            preserve_default=False,
        ),
    ]
