# Generated by Django 4.2.24 on 2025-12-18 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myfinances', '0017_statements_user_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorylist',
            name='unique_category_per_owner',
        ),
        migrations.AddField(
            model_name='categorylist',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='categorylist',
            constraint=models.UniqueConstraint(fields=('user_group', 'name'), name='unique_category_per_group'),
        ),
    ]
