# Generated by Django 4.2.24 on 2026-01-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0018_remove_categorylist_unique_category_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
