# Generated by Django 4.2.24 on 2026-01-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0019_alter_statements_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statements',
            constraint=models.UniqueConstraint(fields=('user_group', 'Posting_Date', 'Description',
                                               'Amount', 'Balance', 'Acct_Info', 'Type', 'Details'), name='unique_transaction_per_group'),
        ),
    ]
