# Generated by Django 2.2.13 on 2021-01-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircrafts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icao24", models.CharField(max_length=20)),
                ("callsign", models.CharField(max_length=20)),
                ("origin_country", models.CharField(max_length=50)),
                ("time_position", models.IntegerField()),
                ("last_contact", models.IntegerField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("baro_altitude", models.FloatField()),
                ("on_ground", models.BooleanField()),
                ("velocity", models.FloatField()),
                ("true_track", models.FloatField()),
                ("vertical_rate", models.FloatField()),
                ("sensors", models.CharField(max_length=20)),
                ("geo_altitude", models.FloatField()),
                ("squawk", models.CharField(max_length=20)),
                ("spi", models.BooleanField()),
                ("position_source", models.IntegerField()),
                ("time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Airports",
            fields=[
                (
                    "AirportID",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="AirportID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=100)),
                ("Country", models.CharField(max_length=70)),
                ("IATA", models.CharField(max_length=70)),
                ("ICAO", models.CharField(max_length=70)),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
                ("Altitude", models.FloatField()),
                ("Timezone", models.CharField(max_length=70)),
                ("DST", models.CharField(max_length=70)),
                ("Tzdatabasetimezone", models.CharField(max_length=70)),
                ("Type", models.CharField(max_length=70)),
                ("Source", models.CharField(max_length=70)),
            ],
        ),
    ]
