# Generated by Django 2.2.13 on 2021-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrafficapp', '0002_countrylatlon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrylatlon',
            name='countryID',
        ),
        migrations.AlterField(
            model_name='countrylatlon',
            name='country',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
