# Generated by Django 2.2.13 on 2021-02-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrafficapp', '0004_clientipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientipaddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clientipaddress',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
