# Generated by Django 4.2.24 on 2025-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrafficapp', '0006_auto_20210824_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
